//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 02:25:32 AM EDT 
//


package model.untransformed.placement;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import model.untransformed.common.PowerType;


/**
 * <p>Java class for military_installment_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="military_installment_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="owner" type="{model/untransformed/common}power_type"/&gt;
 *         &lt;element name="troop_group" type="{model/untransformed/placement}troop_group_type" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "military_installment_type", propOrder = {
    "owner",
    "troopGroup"
})
public class MilitaryInstallmentType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PowerType owner;
    @XmlElement(name = "troop_group", required = true)
    protected List<TroopGroupType> troopGroup;

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link PowerType }
     *     
     */
    public PowerType getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerType }
     *     
     */
    public void setOwner(PowerType value) {
        this.owner = value;
    }

    /**
     * Gets the value of the troopGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the troopGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTroopGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TroopGroupType }
     * 
     * 
     */
    public List<TroopGroupType> getTroopGroup() {
        if (troopGroup == null) {
            troopGroup = new ArrayList<TroopGroupType>();
        }
        return this.troopGroup;
    }

}
