//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 02:25:32 AM EDT 
//


package model.untransformed.placement;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for military_presence_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="military_presence_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="area_ref" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="military_installment" type="{model/untransformed/placement}military_installment_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "military_presence_type", propOrder = {
    "areaRef",
    "militaryInstallment"
})
public class MilitaryPresenceType {

    @XmlElement(name = "area_ref")
    protected int areaRef;
    @XmlElement(name = "military_installment")
    protected List<MilitaryInstallmentType> militaryInstallment;

    /**
     * Gets the value of the areaRef property.
     * 
     */
    public int getAreaRef() {
        return areaRef;
    }

    /**
     * Sets the value of the areaRef property.
     * 
     */
    public void setAreaRef(int value) {
        this.areaRef = value;
    }

    /**
     * Gets the value of the militaryInstallment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the militaryInstallment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMilitaryInstallment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MilitaryInstallmentType }
     * 
     * 
     */
    public List<MilitaryInstallmentType> getMilitaryInstallment() {
        if (militaryInstallment == null) {
            militaryInstallment = new ArrayList<MilitaryInstallmentType>();
        }
        return this.militaryInstallment;
    }

}
