//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 02:25:32 AM EDT 
//


package model.untransformed.placement;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.untransformed.placement package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.untransformed.placement
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlacementType }
     * 
     */
    public PlacementType createPlacementType() {
        return new PlacementType();
    }

    /**
     * Create an instance of {@link MilitaryPresenceType }
     * 
     */
    public MilitaryPresenceType createMilitaryPresenceType() {
        return new MilitaryPresenceType();
    }

    /**
     * Create an instance of {@link MilitaryInstallmentType }
     * 
     */
    public MilitaryInstallmentType createMilitaryInstallmentType() {
        return new MilitaryInstallmentType();
    }

    /**
     * Create an instance of {@link TroopGroupType }
     * 
     */
    public TroopGroupType createTroopGroupType() {
        return new TroopGroupType();
    }

    /**
     * Create an instance of {@link TransportCargoType }
     * 
     */
    public TransportCargoType createTransportCargoType() {
        return new TransportCargoType();
    }

}
