//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 02:25:32 AM EDT 
//


package model.untransformed.delta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import model.untransformed.common.TurnPhaseType;
import model.untransformed.placement.MilitaryInstallmentType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="purchase_units"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="phase" type="{model/untransformed/common}turn_phase_type"/&gt;
 *                   &lt;element name="purchase" type="{model/untransformed/placement}military_installment_type"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="combat_move"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="phase" type="{model/untransformed/common}turn_phase_type"/&gt;
 *                   &lt;element name="movement" type="{model/untransformed/delta}military_installment_movement_type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="noncombat_move"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="phase" type="{model/untransformed/common}turn_phase_type"/&gt;
 *                   &lt;element name="movement" type="{model/untransformed/delta}military_installment_movement_type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="mobilize_new_units"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="phase" type="{model/untransformed/common}turn_phase_type"/&gt;
 *                   &lt;element name="mobilization" type="{model/untransformed/delta}unit_mobilization_type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "purchaseUnits",
    "combatMove",
    "noncombatMove",
    "mobilizeNewUnits"
})
@XmlRootElement(name = "delta_type")
public class DeltaType {

    @XmlElement(name = "purchase_units")
    protected DeltaType.PurchaseUnits purchaseUnits;
    @XmlElement(name = "combat_move")
    protected DeltaType.CombatMove combatMove;
    @XmlElement(name = "noncombat_move")
    protected DeltaType.NoncombatMove noncombatMove;
    @XmlElement(name = "mobilize_new_units")
    protected DeltaType.MobilizeNewUnits mobilizeNewUnits;

    /**
     * Gets the value of the purchaseUnits property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaType.PurchaseUnits }
     *     
     */
    public DeltaType.PurchaseUnits getPurchaseUnits() {
        return purchaseUnits;
    }

    /**
     * Sets the value of the purchaseUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaType.PurchaseUnits }
     *     
     */
    public void setPurchaseUnits(DeltaType.PurchaseUnits value) {
        this.purchaseUnits = value;
    }

    /**
     * Gets the value of the combatMove property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaType.CombatMove }
     *     
     */
    public DeltaType.CombatMove getCombatMove() {
        return combatMove;
    }

    /**
     * Sets the value of the combatMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaType.CombatMove }
     *     
     */
    public void setCombatMove(DeltaType.CombatMove value) {
        this.combatMove = value;
    }

    /**
     * Gets the value of the noncombatMove property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaType.NoncombatMove }
     *     
     */
    public DeltaType.NoncombatMove getNoncombatMove() {
        return noncombatMove;
    }

    /**
     * Sets the value of the noncombatMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaType.NoncombatMove }
     *     
     */
    public void setNoncombatMove(DeltaType.NoncombatMove value) {
        this.noncombatMove = value;
    }

    /**
     * Gets the value of the mobilizeNewUnits property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaType.MobilizeNewUnits }
     *     
     */
    public DeltaType.MobilizeNewUnits getMobilizeNewUnits() {
        return mobilizeNewUnits;
    }

    /**
     * Sets the value of the mobilizeNewUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaType.MobilizeNewUnits }
     *     
     */
    public void setMobilizeNewUnits(DeltaType.MobilizeNewUnits value) {
        this.mobilizeNewUnits = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="phase" type="{model/untransformed/common}turn_phase_type"/&gt;
     *         &lt;element name="movement" type="{model/untransformed/delta}military_installment_movement_type" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "phase",
        "movement"
    })
    public static class CombatMove {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TurnPhaseType phase;
        @XmlElement(required = true)
        protected List<MilitaryInstallmentMovementType> movement;

        /**
         * Gets the value of the phase property.
         * 
         * @return
         *     possible object is
         *     {@link TurnPhaseType }
         *     
         */
        public TurnPhaseType getPhase() {
            return phase;
        }

        /**
         * Sets the value of the phase property.
         * 
         * @param value
         *     allowed object is
         *     {@link TurnPhaseType }
         *     
         */
        public void setPhase(TurnPhaseType value) {
            this.phase = value;
        }

        /**
         * Gets the value of the movement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the movement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMovement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MilitaryInstallmentMovementType }
         * 
         * 
         */
        public List<MilitaryInstallmentMovementType> getMovement() {
            if (movement == null) {
                movement = new ArrayList<MilitaryInstallmentMovementType>();
            }
            return this.movement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="phase" type="{model/untransformed/common}turn_phase_type"/&gt;
     *         &lt;element name="mobilization" type="{model/untransformed/delta}unit_mobilization_type" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "phase",
        "mobilization"
    })
    public static class MobilizeNewUnits {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TurnPhaseType phase;
        @XmlElement(required = true)
        protected List<UnitMobilizationType> mobilization;

        /**
         * Gets the value of the phase property.
         * 
         * @return
         *     possible object is
         *     {@link TurnPhaseType }
         *     
         */
        public TurnPhaseType getPhase() {
            return phase;
        }

        /**
         * Sets the value of the phase property.
         * 
         * @param value
         *     allowed object is
         *     {@link TurnPhaseType }
         *     
         */
        public void setPhase(TurnPhaseType value) {
            this.phase = value;
        }

        /**
         * Gets the value of the mobilization property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mobilization property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMobilization().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UnitMobilizationType }
         * 
         * 
         */
        public List<UnitMobilizationType> getMobilization() {
            if (mobilization == null) {
                mobilization = new ArrayList<UnitMobilizationType>();
            }
            return this.mobilization;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="phase" type="{model/untransformed/common}turn_phase_type"/&gt;
     *         &lt;element name="movement" type="{model/untransformed/delta}military_installment_movement_type" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "phase",
        "movement"
    })
    public static class NoncombatMove {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TurnPhaseType phase;
        @XmlElement(required = true)
        protected List<MilitaryInstallmentMovementType> movement;

        /**
         * Gets the value of the phase property.
         * 
         * @return
         *     possible object is
         *     {@link TurnPhaseType }
         *     
         */
        public TurnPhaseType getPhase() {
            return phase;
        }

        /**
         * Sets the value of the phase property.
         * 
         * @param value
         *     allowed object is
         *     {@link TurnPhaseType }
         *     
         */
        public void setPhase(TurnPhaseType value) {
            this.phase = value;
        }

        /**
         * Gets the value of the movement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the movement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMovement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MilitaryInstallmentMovementType }
         * 
         * 
         */
        public List<MilitaryInstallmentMovementType> getMovement() {
            if (movement == null) {
                movement = new ArrayList<MilitaryInstallmentMovementType>();
            }
            return this.movement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="phase" type="{model/untransformed/common}turn_phase_type"/&gt;
     *         &lt;element name="purchase" type="{model/untransformed/placement}military_installment_type"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "phase",
        "purchase"
    })
    public static class PurchaseUnits {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TurnPhaseType phase;
        @XmlElement(required = true)
        protected MilitaryInstallmentType purchase;

        /**
         * Gets the value of the phase property.
         * 
         * @return
         *     possible object is
         *     {@link TurnPhaseType }
         *     
         */
        public TurnPhaseType getPhase() {
            return phase;
        }

        /**
         * Sets the value of the phase property.
         * 
         * @param value
         *     allowed object is
         *     {@link TurnPhaseType }
         *     
         */
        public void setPhase(TurnPhaseType value) {
            this.phase = value;
        }

        /**
         * Gets the value of the purchase property.
         * 
         * @return
         *     possible object is
         *     {@link MilitaryInstallmentType }
         *     
         */
        public MilitaryInstallmentType getPurchase() {
            return purchase;
        }

        /**
         * Sets the value of the purchase property.
         * 
         * @param value
         *     allowed object is
         *     {@link MilitaryInstallmentType }
         *     
         */
        public void setPurchase(MilitaryInstallmentType value) {
            this.purchase = value;
        }

    }

}
