//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 02:25:32 AM EDT 
//


package model.untransformed.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import model.untransformed.placement.MilitaryInstallmentType;


/**
 * <p>Java class for military_installment_movement_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="military_installment_movement_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="military_installment" type="{model/untransformed/placement}military_installment_type"/&gt;
 *         &lt;element name="area_from" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="area_to" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "military_installment_movement_type", propOrder = {
    "militaryInstallment",
    "areaFrom",
    "areaTo"
})
public class MilitaryInstallmentMovementType {

    @XmlElement(name = "military_installment", required = true)
    protected MilitaryInstallmentType militaryInstallment;
    @XmlElement(name = "area_from")
    protected int areaFrom;
    @XmlElement(name = "area_to")
    protected int areaTo;

    /**
     * Gets the value of the militaryInstallment property.
     * 
     * @return
     *     possible object is
     *     {@link MilitaryInstallmentType }
     *     
     */
    public MilitaryInstallmentType getMilitaryInstallment() {
        return militaryInstallment;
    }

    /**
     * Sets the value of the militaryInstallment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MilitaryInstallmentType }
     *     
     */
    public void setMilitaryInstallment(MilitaryInstallmentType value) {
        this.militaryInstallment = value;
    }

    /**
     * Gets the value of the areaFrom property.
     * 
     */
    public int getAreaFrom() {
        return areaFrom;
    }

    /**
     * Sets the value of the areaFrom property.
     * 
     */
    public void setAreaFrom(int value) {
        this.areaFrom = value;
    }

    /**
     * Gets the value of the areaTo property.
     * 
     */
    public int getAreaTo() {
        return areaTo;
    }

    /**
     * Sets the value of the areaTo property.
     * 
     */
    public void setAreaTo(int value) {
        this.areaTo = value;
    }

}
