//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 02:25:32 AM EDT 
//


package model.untransformed.delta;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.untransformed.delta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.untransformed.delta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeltaType }
     * 
     */
    public DeltaType createDeltaType() {
        return new DeltaType();
    }

    /**
     * Create an instance of {@link DeltaType.PurchaseUnits }
     * 
     */
    public DeltaType.PurchaseUnits createDeltaTypePurchaseUnits() {
        return new DeltaType.PurchaseUnits();
    }

    /**
     * Create an instance of {@link DeltaType.CombatMove }
     * 
     */
    public DeltaType.CombatMove createDeltaTypeCombatMove() {
        return new DeltaType.CombatMove();
    }

    /**
     * Create an instance of {@link DeltaType.NoncombatMove }
     * 
     */
    public DeltaType.NoncombatMove createDeltaTypeNoncombatMove() {
        return new DeltaType.NoncombatMove();
    }

    /**
     * Create an instance of {@link DeltaType.MobilizeNewUnits }
     * 
     */
    public DeltaType.MobilizeNewUnits createDeltaTypeMobilizeNewUnits() {
        return new DeltaType.MobilizeNewUnits();
    }

    /**
     * Create an instance of {@link UnitPurchaseType }
     * 
     */
    public UnitPurchaseType createUnitPurchaseType() {
        return new UnitPurchaseType();
    }

    /**
     * Create an instance of {@link MilitaryInstallmentMovementType }
     * 
     */
    public MilitaryInstallmentMovementType createMilitaryInstallmentMovementType() {
        return new MilitaryInstallmentMovementType();
    }

    /**
     * Create an instance of {@link UnitMobilizationType }
     * 
     */
    public UnitMobilizationType createUnitMobilizationType() {
        return new UnitMobilizationType();
    }

}
