//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 02:25:32 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "model/untransformed/map", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model.untransformed.map;
