//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 02:25:32 AM EDT 
//


package model.untransformed.power;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import model.untransformed.common.PowerType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="power_holdings" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="power" type="{model/untransformed/common}power_type"/&gt;
 *                   &lt;element name="money" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="controlled_area" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "powerHoldings"
})
@XmlRootElement(name = "powers_type")
public class PowersType {

    @XmlElement(name = "power_holdings", required = true)
    protected List<PowersType.PowerHoldings> powerHoldings;

    /**
     * Gets the value of the powerHoldings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the powerHoldings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPowerHoldings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PowersType.PowerHoldings }
     * 
     * 
     */
    public List<PowersType.PowerHoldings> getPowerHoldings() {
        if (powerHoldings == null) {
            powerHoldings = new ArrayList<PowersType.PowerHoldings>();
        }
        return this.powerHoldings;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="power" type="{model/untransformed/common}power_type"/&gt;
     *         &lt;element name="money" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="controlled_area" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "power",
        "money",
        "controlledArea"
    })
    public static class PowerHoldings {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected PowerType power;
        protected int money;
        @XmlElement(name = "controlled_area", type = Integer.class)
        protected List<Integer> controlledArea;

        /**
         * Gets the value of the power property.
         * 
         * @return
         *     possible object is
         *     {@link PowerType }
         *     
         */
        public PowerType getPower() {
            return power;
        }

        /**
         * Sets the value of the power property.
         * 
         * @param value
         *     allowed object is
         *     {@link PowerType }
         *     
         */
        public void setPower(PowerType value) {
            this.power = value;
        }

        /**
         * Gets the value of the money property.
         * 
         */
        public int getMoney() {
            return money;
        }

        /**
         * Sets the value of the money property.
         * 
         */
        public void setMoney(int value) {
            this.money = value;
        }

        /**
         * Gets the value of the controlledArea property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the controlledArea property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getControlledArea().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getControlledArea() {
            if (controlledArea == null) {
                controlledArea = new ArrayList<Integer>();
            }
            return this.controlledArea;
        }

    }

}
